BAH-3127 | Updated Readme and Implemented Basic Github Action Build Workflow
Bahmni/whatsapp-bahmni-service pull request #2
Opened 2023-07-30 10:16 UTC by Aniket28dot

### Readme and Build Workflow Updates:
- Java Version, Maven Version
- WhatsApp API Set Up steps
- Webhook Configuration Steps
- Basic GitHub action workflow that performs build of the Microservice.

Jira Ticket: [link](https://bahmni.atlassian.net/browse/BAH-3127)

2023-07-31 07:52 UTC, rahu1ramesh requested changes

2023-07-31 07:52 UTC, rahu1ramesh commented on .DS_Store
Please add `.DS_Store` to the `.gitignore`. If you don't have a `.gitignore`, create one and add the files and folders that need not be committed.

2023-07-31 07:52 UTC, rahu1ramesh commented on .github/workflows/build.yml
> +  workflow_dispatch:
You can remove the `workflow_dispatch` for now. You can read further about `workflow_dispatch` [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch).

2023-07-31 07:52 UTC, rahu1ramesh commented on .github/workflows/build.yml
> +      - name: Set up JDK 20.0.1
The choice of `JDK 20.0.1` for this Pull Request needs clarification. If the project's Java requirements do not specifically necessitate `JDK 20.0.1`, it is recommended to use `JDK 1.8` instead.
Please provide an explanation for the JDK selection or consider using `JDK 1.8`.

2023-07-31 07:52 UTC, rahu1ramesh commented on .github/workflows/build.yml
> +          java-version: 20.0.1
The choice of `JDK 20.0.1` for this Pull Request needs clarification. If the project's Java requirements do not specifically necessitate `JDK 20.0.1`, it is recommended to use `JDK 1.8` instead.
Please provide an explanation for the JDK selection or consider using `JDK 1.8`.

2023-07-31 07:52 UTC, rahu1ramesh commented on .mvn/wrapper/maven-wrapper.jar
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on .mvn/wrapper/maven-wrapper.properties
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on README.md
> +java version 20.0.1
The choice of `JDK 20.0.1` for this Pull Request needs clarification. If the project's Java requirements do not specifically necessitate `JDK 20.0.1`, it is recommended to use `JDK 1.8` instead.
Please provide an explanation for the JDK selection or consider using `JDK 1.8`.

2023-07-31 07:52 UTC, rahu1ramesh commented on README.md
> +# Maven Version
Kindly refrain from adding separate sub headings for java and maven version requirements. Add a sub heading called `Requirements` and including the necessary details under it.

2023-07-31 07:52 UTC, rahu1ramesh commented on README.md
Please do add a section on how to clone the repo and set up the project. You can refer this [README](https://github.com/Bahmni/bahmni-core/tree/master#clone-the-repository-and-build-the-omod) for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on mvnw
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on mvnw.cmd
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on pom.xml
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on src/main/java/org/bahmni/whatsapp/appointments/WhatsAppAPIController.java
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on src/main/java/org/bahmni/whatsapp/appointments/WhatsappBahmniServiceApplication.java
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on src/main/resources/application.properties
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on src/test/java/org/bahmni/whatsapp/appointments/WhatsAppAPIControllerTest.java
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 07:52 UTC, rahu1ramesh commented on src/test/java/org/bahmni/whatsapp/appointments/WhatsappBahmniServiceApplicationTests.java
These changes are not part of the card BAH-3127, add a card for what this changes are for and then kindly raise another PR for the same.

2023-07-31 12:51 UTC, Aniket28dot commented on .DS_Store
sure will add .DS_Store in git ignore.

2023-08-01 10:09 UTC, Aniket28dot commented on README.md
> +# Maven Version
yes, added the Requirements sections now.

2023-08-01 10:10 UTC, Aniket28dot commented on README.md
yes, added this section for cloning the repo.

2023-08-14 03:57 UTC, rahu1ramesh approved these changes

2023-08-18 05:17 UTC, merged